const List<Map<String, String>> images = [
  {'path': 'lib/images/beardo.png', 'name': 'beardo'},
  {'path': 'lib/images/bhola.png', 'name': 'bhola'},
  {'path': 'lib/images/freestyle.png', 'name': 'freestyle'},
  {'path': 'lib/images/goodboi.png', 'name': 'goodboi'},
  {'path': 'lib/images/gorigori.png', 'name': 'gorigori'},
  {'path': 'lib/images/happyindian.png', 'name': 'happyindian'},
  {'path': 'lib/images/orangewolf.png', 'name': 'orangewolf'},
  {'path': 'lib/images/ponitail.png', 'name': 'ponitail'},
  {'path': 'lib/images/purploo.png', 'name': 'purploo'},
  {'path': 'lib/images/sanyasi.png', 'name': 'sanyasi'},
  {'path': 'lib/images/smile.png', 'name': 'smile'},
  {'path': 'lib/images/tintin.png', 'name': 'tintin'},
  {'path': 'lib/images/nerdy.png', 'name': 'nerdy'},
  {'path': 'lib/images/bush.png', 'name': 'bush'},
  {'path': 'lib/images/lovemelikeyoudo.png', 'name': 'lovemelikeyoudo'},
  {'path': 'lib/images/carefree.png', 'name': 'carefree'},
  {'path': 'lib/images/tate.png', 'name': 'tate'},
];
